### ISSUE TITLE
Fatal Error when opening customizer page.

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [puikinsh/Dazzling#46]
> PHP Fatal error:  Call to undefined method WP_Customize_Manager::add_panel() in /wordpress/wp-content/themes/dazzling/inc/customizer.php on line 35, referer: https://.../wp-admin/widgets.php

Wordpress: `3.8.13 (3.8.2+dfsg-1ubuntu0.1)`
PHP: `5.5.9-1ubuntu4.14`

Let me know if there's any additional information I can provide.

**Comment by puikinsh** [comment]
Make sure to update WordPress to the latest version. The one you use doesn't properly supports panels in Customizer therefore causing errors. Also this version is vulnerable to hundreds of security flaws that have been discovered over the last two years since this version was released. Your website is no safe at all.

**Comment by tjesser-ucdavis-edu** [comment]
Thank you for the information. I had incorrectly assumed that WordPress would be part of Ubuntu's security updates.

Now that I've switched to 4.4, the customizer works correctly. I think this issue can be closed.
